### ISSUE TITLE
nss is not initialised

### ISSUE THREAD

**Issue by rekado** [daviddahl/domcrypt#4]
Having installed domcrypt on FF 20.0, I see this message on the console after running the tests:

```
*** DOMCryptMethods: GenerateCallbackObject() constructor
*** DOMCryptMethods: Worker Error: this.nss is null
*** DOMCryptMethods: Worker Error filename: resource://domcrypt/domcrypt_worker.js
*** DOMCryptMethods: Worker Error line no: 1280
```

None of the crypt methods are working for me; they all return `undefined`.

**Comment by daviddahl** [comment]
gah! I should be able to figure this out this week. Ping me again on Thursday if this is causing you grief.

**Comment by rekado** [comment]
What's going on here is that `DOMCryptMethods.init` is never called. Tracing the initialisation code, I see that the following line doesn't return

```
data = NetUtil.readInputStreamToString(inputStream, inputStream.available());
```

Another thing I see is that the initialisation happens not when the browser starts, but only when some DOMCrypt action is called; when I click on "Run tests" the "generateKeypair" message is sent to the worker, but this will always fail unless the "init" message is received first.

**Comment by daviddahl** [comment]
Running Nightly Firefox, I see things working correctly running the demo: http://domcrypt.org/demos/demo.html - I will d/l Firefox 20 and see what happens. (this is using Linux)

**Comment by rekado** [comment]
After removing `.mozCipher.json`, the initialisation method is indeed called. This time I get this error message:

```
*** DOMCryptMethods: Worker Error: couldn't open library /usr/lib/firefox/xulrunner/libnss3.so
```

In fact, this library does not exist. (I'm on Fedora 18.) It appears that the library is located at /usr/lib/libnss3.so

**Comment by rekado** [comment]
After symlinking the lib to `/usr/lib/xulrunner/libnss3.so` and removing `.mozCipher.json`, things are working just fine. The config file had to be removed, because it was empty. I think DOMCrypt should treat an empty config file (that is generated on errors) as non-existent and overwrite it.

I wonder why Firefox delivers a wrong path to `libnss3.so`.

**EDIT:** this seems to be related: https://bugzilla.mozilla.org/show_bug.cgi?id=583209

Instead of prepending the path obtained by `Services.dirsvc.get("GreD", Ci.nsILocalFile);`, using only the library name might work. I'm going to test that.

**EDIT:** on Fedora 18 it works to simply do `let fullPath = libName;`, i.e. without prepending an explicit library path.

**Comment by daviddahl** [comment]
A new enhancement issue should be added for this config file kerfuffle. Thanks for looking into this. So we need to just add a try/catch for the fedora path issue then.
